<?php

// this is the default array of characters

$characters = [
    [
        'name' => 'Lorelei Moonshadow',
        'race_id' => 1,
        'user_id' => 1,
        'height' => 1.75,
        'weight' => 70,
        'background' => 'Lorelei, a devoted follower of nature, grew up deep in the heart of the enchanted forest of Eldwood. From a young age, she communicated with the spirits of the land and animals, developing a profound connection to the natural world. Guided by the balance of life, she embarked on a journey to preserve the harmony between civilization and the wilderness.',
        'picture' => 'https://th.bing.com/th/id/OIG.N9RIXjzajvFsrfc.SXqA?pid=ImgGn',
        'armor_class' => 15,
        'for' => 12,
        'des' => 14,
        'cos' => 16,
        'int' => 10,
        'sag' => 18,
        'car' => 12,
    ],
    [
        'name' => 'Elyndor Swiftwind',
        'race_id' => 2,
        'user_id' => 1,
        'height' => 1.85,
        'weight' => 65,
        'background' => 'Elyndor, a graceful and agile elf, hails from the mystical realm of Everwood. Raised in the ancient traditions of elven culture, he is a skilled archer and a master of nature magic. Elyndor`s keen senses and deep connection with the forest make him a vigilant guardian of the elven homeland.',
        'picture' => 'https://th.bing.com/th/id/OIG.z.iAJUczPb9XY4kecG90?pid=ImgGn',
        'armor_class' => 16,
        'for' => 14,
        'des' => 18,
        'cos' => 12,
        'int' => 16,
        'sag' => 14,
        'car' => 12,
    ],
    [
        'name' => 'Alistair Ironheart',
        'race_id' => 3,
        'user_id' => 1,
        'height' => 1.78,
        'weight' => 75,
        'background' => 'Alistair, a resilient and versatile human, was born in the bustling city of Eldoria. Growing up in a diverse and cosmopolitan environment, he learned various skills that make him adaptable to different situations. Alistair`s sense of determination and ambition drive him to excel in whatever path he chooses.',
        'picture' => 'https://th.bing.com/th/id/OIG.SdyvUU9KTGiusTAOIatR?pid=ImgGn',
        'armor_class' => 14,
        'for' => 16,
        'des' => 14,
        'cos' => 16,
        'int' => 12,
        'sag' => 12,
        'car' => 14,
    ],
    [
        'name' => 'Glimmer Copperpot',
        'race_id' => 4,
        'user_id' => 1,
        'height' => 0.95,
        'weight' => 20,
        'background' => 'Glimmer, a curious and inventive gnome, hails from the underground city of Rockhaven. Gifted with a keen intellect and a natural affinity for magic, Glimmer is a tinkerer and alchemist. His insatiable curiosity often leads him on quests for rare and exotic materials to fuel his experiments.',
        'picture' => 'https://th.bing.com/th/id/OIG.L3TU5LpQOeL2W3oSURae?pid=ImgGn',
        'armor_class' => 12,
        'for' => 10,
        'des' => 16,
        'cos' => 12,
        'int' => 18,
        'sag' => 14,
        'car' => 10,
    ],
    [
        'name' => 'Thorin Stonehammer',
        'race_id' => 5,
        'user_id' => 1,
        'height' => 1.4,
        'weight' => 80,
        'background' => 'Thorin, a stout and resilient dwarf, hails from the mountainous kingdom of Ironpeak. Born into a proud clan of skilled blacksmiths and miners, Thorin carries the craftsmanship of his people. His unyielding determination and loyalty make him a stalwart defender of his homeland and a formidable companion in battle.',
        'picture' => 'https://th.bing.com/th/id/OIG.KPZixa_62PkWV9_GELpi?pid=ImgGn',
        'armor_class' => 16,
        'for' => 18,
        'des' => 12,
        'cos' => 16,
        'int' => 10,
        'sag' => 14,
        'car' => 10,
    ],
    [
        'name' => 'Grommash Bloodaxe',
        'race_id' => 6,
        'user_id' => 1,
        'height' => 1.9,
        'weight' => 120,
        'background' => 'Grommash, a fierce and battle-hardened orc, was raised in the harsh deserts of the Bloodlands. From a young age, he proved himself in tribal conflicts, earning the title of Bloodaxe. Guided by a warrior`s code, Grommash seeks glory in the heat of battle, fueled by the spirit of his ancestors.',
        'picture' => 'https://th.bing.com/th/id/OIG.FR12RLoW4fI7_.e8xG8N?pid=ImgGn',
        'armor_class' => 15,
        'for' => 20,
        'des' => 12,
        'cos' => 14,
        'int' => 8,
        'sag' => 10,
        'car' => 12,
    ],
    [
        'name' => 'Lilith Nightshade',
        'race_id' => 7,
        'user_id' => 1,
        'height' => 1.75,
        'weight' => 60,
        'background' => 'Lilith, a cunning and mysterious drow, was born into the secretive society of the Underdark. Trained in the arts of subterfuge and dark magic, Lilith navigates the treacherous politics of her homeland. Driven by ambition, she seeks power and influence to shape the destiny of the drow and secure her place among the elite.',
        'picture' => 'https://th.bing.com/th/id/OIG.07NbwPkUFYqe9pUvOEdM?w=1024&h=1024&rs=1&pid=ImgDetMain',
        'armor_class' => 14,
        'for' => 12,
        'des' => 18,
        'cos' => 10,
        'int' => 16,
        'sag' => 14,
        'car' => 16,
    ],
    [
        'name' => 'Sirion the Valiant',
        'race_id' => 1,
        'user_id' => 1,
        'height' => 1.83,
        'weight' => 90,
        'background' => 'Sirion, born into the noble lineage of the Valiants, grew up amidst the clash of swords and the echo of war horns. Trained from a young age in the art of combat, he proved his mettle on the battlefield, earning accolades and the respect of his peers. However, a sense of duty and justice led him to embark on a quest to protect the realm from ancient evils and unseen threats.',
        'picture' => 'https://quellicheilbardo.it/wp-content/uploads/2020/07/Guerriero-1-1.jpg',
        'armor_class'  => 18,
        'for' => 16,
        'des' => 16,
        'cos' => 14,
        'int' => 10,
        'sag' => 4,
        'car' => 16
    ],
    [
        'name' => 'Elena Swiftblade',
        'race_id' => 2,
        'user_id' => 1,
        'height' => 1.70,
        'weight' => 65,
        'background' => 'Elena, a skilled elven rogue, honed her agility and stealth in the dense forests of Eldoria. Her quick reflexes and sharp wit make her a formidable opponent in both combat and trickery. Driven by a desire for freedom, she travels the lands in search of ancient artifacts and hidden treasures.',
        'picture' => 'https://th.bing.com/th/id/OIG.ZBr7KDa_BAoDpcDxrOYn?pid=ImgGn',
        'armor_class' => 15,
        'for' => 12,
        'des' => 18,
        'cos' => 10,
        'int' => 14,
        'sag' => 12,
        'car' => 14
    ],
];
