<?php

$races = [
    [
        'name' => 'Druid',
        'description' => 'Mystical beings connected to nature, capable of shape-shifting and harnessing natural magic.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.2EFeQqEo.uXt1eWrrBKQ?pid=ImgGn',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 2,
        'mod_car' => 0,
    ],
    [
        'name' => 'Elf',
        'description' => 'Graceful and long-lived beings with a deep connection to nature and keen senses.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.V_L37BEccKcDCn8WB3W4?pid=ImgGn',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Human',
        'description' => 'Adaptable and ambitious creatures known for their diversity and capacity for learning.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.tQhFh8HG9tZPwMqXiXcp?pid=ImgGn',
        'mod_for' => 1,
        'mod_des' => 1,
        'mod_cos' => 1,
        'mod_int' => 1,
        'mod_sag' => 1,
        'mod_car' => 1,
    ],
    [
        'name' => 'Gnome',
        'description' => 'Inventive and curious small folk with a talent for tinkering and magic.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.bUrPHdINZ3bk6s1LDst5?w=1024&h=1024&rs=1&pid=ImgDetMain',
        'mod_for' => 0,
        'mod_des' => 1,
        'mod_cos' => 0,
        'mod_int' => 2,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Dwarf',
        'description' => 'Sturdy and resilient beings with a strong affinity for craftsmanship and mining.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.9ZoWaM_iN.ib4KT1okga?w=1024&h=1024&rs=1&pid=ImgDetMain',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 2,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Orc',
        'description' => 'Fierce and brutal warriors known for their strength and determination in battle.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.hkSc7ZR4UC4QBzk0Sa1p?pid=ImgGn',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => -1,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Drow',
        'description' => 'Cunning and elusive dark elves with a proficiency in subterfuge and dark magic.',
        'picture_link' => 'https://th.bing.com/th/id/OIG.f7hRRYZJ375lc2aVOWsC?pid=ImgGn',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
];
