<?php

$races = [
    [
        'name' => 'Dragonborn',
        'description' => 'Proud and honorable dragon-like humanoids with a breath weapon.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 1,
    ],
    [
        'name' => 'Dwarf',
        'description' => 'Stout and sturdy humanoids known for their craftsmanship and resilience.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 2,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Elf',
        'description' => 'Elegant and long-lived humanoids with a deep connection to nature and magic.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Gnome',
        'description' => 'Inventive and curious humanoids known for their love of tinkering and illusion magic.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 2,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Half-Elf',
        'description' => 'A mix of human and elf heritage, often charismatic and adaptable.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 2,
    ],
    [
        'name' => 'Half-Orc',
        'description' => 'Combining human and orc bloodlines, strong and resilient warriors.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Halfling',
        'description' => 'Small and nimble humanoids known for their luck and agility.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 1,
    ],
    [
        'name' => 'Human',
        'description' => 'Versatile and ambitious beings known for their adaptability.',
        'mod_for' => 1,
        'mod_des' => 1,
        'mod_cos' => 1,
        'mod_int' => 1,
        'mod_sag' => 1,
        'mod_car' => 1,
    ],
    [
        'name' => 'Tiefling',
        'description' => 'Beings with infernal heritage, often displaying demonic traits.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 2,
    ],
    [
        'name' => 'Aarakocra',
        'description' => 'Bird-like beings with wings and a strong connection to the sky.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Aasimar',
        'description' => 'Celestial-touched beings with a divine connection.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 2,
    ],
    [
        'name' => 'Changeling',
        'description' => 'Shape-shifters with the ability to alter their appearance at will.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 2,
    ],
    [
        'name' => 'Deep Gnome',
        'description' => 'Gnomes adapted to the subterranean life with innate magic abilities.',
        'mod_for' => 0,
        'mod_des' => 1,
        'mod_cos' => 0,
        'mod_int' => 2,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Duergar',
        'description' => 'Gray-skinned dwarves from the Underdark with an affinity for magic.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 2,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Eladrin',
        'description' => 'High elves tied to the Feywild with a connection to the changing seasons.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Fairy',
        'description' => 'Tiny, magical beings with wings and a playful nature.',
        'mod_for' => -2,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 2,
    ],
    [
        'name' => 'Firbolg',
        'description' => 'Large and gentle beings with a connection to nature.',
        'mod_for' => 1,
        'mod_des' => 0,
        'mod_cos' => 2,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Genasi (Air)',
        'description' => 'Elemental-infused beings with ties to the air element.',
        'mod_for' => 0,
        'mod_des' => 1,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Genasi (Earth)',
        'description' => 'Elemental-infused beings with ties to the earth element.',
        'mod_for' => 1,
        'mod_des' => 0,
        'mod_cos' => 2,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Genasi (Fire)',
        'description' => 'Elemental-infused beings with ties to the fire element.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 2,
    ],
    [
        'name' => 'Genasi (Water)',
        'description' => 'Elemental-infused beings with ties to the water element.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Githyanki',
        'description' => 'Astral-faring warriors known for their psionic abilities.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Githzerai',
        'description' => 'Disciplined and psychic humanoids with a strong will.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 2,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Goliath',
        'description' => 'Majestic and powerful humanoids with a strong and imposing presence.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Harengon',
        'description' => 'Swift and agile rabbit-like humanoids with a love for speed.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 1,
    ],
    [
        'name' => 'Kenku',
        'description' => 'Bird-like humanoids known for their mimicry and artistic talents.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 1,
    ],
    [
        'name' => 'Locathah',
        'description' => 'Aquatic humanoids with fish-like features and an affinity for the sea.',
        'mod_for' => 0,
        'mod_des' => 1,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Owlin',
        'description' => 'Owl-like humanoid creatures with keen senses and a connection to the night.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 2,
    ],
    [
        'name' => 'Satyr',
        'description' => 'Playful and musical beings with goat-like features.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Sea Elf',
        'description' => 'Elves adapted to underwater life with a natural affinity for the ocean.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Shadar-Kai',
        'description' => 'Shadowfell-touched elves with a connection to darkness and the Shadowfell.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Tabaxi',
        'description' => 'Feline humanoids with agility and a love for exploration.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 1,
    ],
    [
        'name' => 'Tortle',
        'description' => 'Humanoid tortoises known for their resilience and natural armor.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Triton',
        'description' => 'Aquatic beings with a connection to the seas and underwater realms.',
        'mod_for' => 1,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Verdan',
        'description' => 'Small and adaptable plant-like beings with unique abilities.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 2,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Bugbear',
        'description' => 'Large and imposing goblinoids known for their strength and intimidation.',
        'mod_for' => 2,
        'mod_des' => 1,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Centaur',
        'description' => 'Majestic beings with the upper body of a human and the lower body of a horse.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Goblin',
        'description' => 'Small and cunning goblinoids known for their mischief and agility.',
        'mod_for' => 0,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Grung',
        'description' => 'Small and brightly colored amphibious humanoids with toxic skin.',
        'mod_for' => -1,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => -1,
    ],
    [
        'name' => 'Hobgoblin',
        'description' => 'Disciplined goblinoids known for their military prowess and strategic minds.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Kobold',
        'description' => 'Small, reptilian humanoids known for their cunning and traps.',
        'mod_for' => -2,
        'mod_des' => 2,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => -1,
    ],
    [
        'name' => 'Lizardfolk',
        'description' => 'Reptilian humanoids known for their connection to marshes and swamps.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Minotaur',
        'description' => 'Powerful humanoid creatures with the head of a bull.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 0,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
    [
        'name' => 'Orc',
        'description' => 'Strong and aggressive humanoid creatures often associated with brutality.',
        'mod_for' => 2,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => -1,
        'mod_sag' => 0,
        'mod_car' => -1,
    ],
    [
        'name' => 'Shifter',
        'description' => 'Humanoids with the ability to take on bestial aspects, reflecting a primal nature.',
        'mod_for' => 0,
        'mod_des' => 1,
        'mod_cos' => 0,
        'mod_int' => 0,
        'mod_sag' => 1,
        'mod_car' => 0,
    ],
    [
        'name' => 'Yuan-Ti',
        'description' => 'Serpentine humanoids known for their cunning and magical abilities.',
        'mod_for' => 0,
        'mod_des' => 0,
        'mod_cos' => 1,
        'mod_int' => 1,
        'mod_sag' => 0,
        'mod_car' => 0,
    ],
];
